---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kestra
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kestra
      version: '>0.0.0'
      sourceRef:
        kind: HelmRepository
        name: kestra-repository
        namespace: flux-system
  values:
    # Global security context for running containers
    securityContext:
      privileged: false

    deployments:
      standalone:
        enabled: true
      webserver:
        enabled: false
      executor:
        enabled: false
      indexer:
        enabled: false
      scheduler:
        enabled: false
      worker:
        enabled: false
    postgresql:
      enabled: true
    minio:
      enabled: true
    dind:
      enabled: true
      image:
        image: docker
        tag: dind
      args:
        - --log-level=fatal
      # Add security context to run as root
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        privileged: true