# Kestra deployment configuration
# These values will be used by the HelmRelease

# Configure Kestra components - default to using the standalone mode
deployments:
  standalone:
    enabled: true
  webserver:
    enabled: false
  executor:
    enabled: false
  indexer:
    enabled: false
  scheduler:
    enabled: false
  worker:
    enabled: false

# Enable required dependencies
postgresql:
  enabled: true
minio:
  enabled: true
dind:
  enabled: true
  image:
    image: docker
    tag: dind
  args:
    - --log-level=fatal